### PR TITLE
Pin protoc to recent version

### PR DESCRIPTION
**Pull request by adleong**
We add a `bin/protoc` script to use a specific version of `protoc` instead of whatever happens to be installed on the local system.  We set the protoc version to the current latest, 3.18.0.

Signed-off-by: Alex Leong <alex@buoyant.io>

### CODE REVIEW

**Comment by cpretzer** [comment]
I get the same warnings that @olix0r mentioned on both macOS and linux (PopOS). In addition `make test` fails with these messages

```
go test ./...
cmd/server.go:8:2: found packages proto (Emoji.pb.go) and _ (Emoji_grpc.pb.go) in /home/pineapple/projects/buoyant/emojivoto/emojivoto-web/gen/proto
cmd/server.go:8:2: found packages proto (Emoji.pb.go) and _ (Emoji_grpc.pb.go) in /home/pineapple/projects/buoyant/emojivoto/emojivoto-web/gen/proto
```

I suspect that there is something in my go env that is different, any thoughts on what I should look for?

**Comment by olix0r** [comment]
We tracked this down to a version mismatch of `protoc-gen-go-grpc`:

```
 protoc-gen-go-grpc --version
protoc-gen-go-grpc 1.1.0
➜  emojivoto git:(alex/protoc) md5 $(which protoc-gen-go-grpc)
MD5 (/Users/alexanderleong/go/bin/protoc-gen-go-grpc) = f2992e5e502e92496f521a3b393bee06
➜  emojivoto git:(alex/protoc) go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.1
➜  emojivoto git:(alex/protoc) protoc-gen-go-grpc --version
protoc-gen-go-grpc 1.1.0
➜  emojivoto git:(alex/protoc) md5 $(which protoc-gen-go-grpc)
MD5 (/Users/alexanderleong/go/bin/protoc-gen-go-grpc) = 49adefec69121e144aad46ccb30f9138
```

**Review by olix0r — APPROVED** [review]
Works for me!

Would be great to get CI to verify this stuff going forward; and even better if we could figure out how to make the build reproducible, but I digress.

**Comment by rbg** [comment]
is it possible to merge this ?

**Pull request merged**
